### PR TITLE
[IIO] bugfixes related to errors from yocto run

### LINKED ISSUE #1353: [UNITTES] Unittest IIO is not ended with yocto.
When I run the unittest_src_iio in the qemu which generated by yocto project, it is not ended as below.
Need to be fixed.

```
Poky (Yocto Project Reference Distro) 2.6.1 qemux86-64 /dev/ttyS0

qemux86-64 login: root
root@qemux86-64:~# export LD_LIBRARY_PATH=/usr/lib/gstreamer-1.0:$LD_LIBRARY_PATH; /usr/lib/nnstreamer/unittest/unittest_src_iio --gst-plugin-path=/usr/lib/gstreamer-1.0
[==========] Running 13 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 13 tests from test_tensor_src_iio
[ RUN      ] test_tensor_src_iio.properties
[       OK ] test_tensor_src_iio.properties (47 ms)
[ RUN      ] test_tensor_src_iio.start_stop

(unittest_src_iio:369): GLib-CRITICAL **: 09:58:34.879: g_file_test: assertion 'filename != NULL' failed
[       OK ] test_tensor_src_iio.start_stop (195 ms)
[ RUN      ] test_tensor_src_iio.data_verify_no_trigger_bits4_alternate1

------ HANGING!
```

a0339eb049e6f1ad461f4be3379ea59623081a97 is OK, though.

### PR DESCRIPTION
**Pull request by kparichay**
1. set base src as async, resolves the error of hanging
  without setting base_src as async, _start_complete gets called twice
2. initializing log_file to NULL
3. NULL check for variable before using it for remove/rmdir
4. remove _query function, was incomplete, and complete function
  was same as parent class function

resolve #1353, nnsuite/TAOS-CI#489

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Comment by kparichay** [comment]
@again4you Please review this PR as well as consider setting  `gst_base_src_set_async (GST_BASE_SRC (self), TRUE);` for nnstreamer-ros src as well.

File: gst/nnstreamer/tensor_source/tensor_src_iio.c [hunk 1]
```diff
@@ -423,6 +421,11 @@ gst_tensor_src_iio_init (GstTensorSrcIIO * self)
   gst_base_src_set_live (GST_BASE_SRC (self), TRUE);
   /** set the timestamps on each buffer */
   gst_base_src_set_do_timestamp (GST_BASE_SRC (self), TRUE);
+  /**
+   * set async is necessary to make state change async
+   * sync state changes does not need calling _start_complete() from _start()
+   */
+  gst_base_src_set_async (GST_BASE_SRC (self), TRUE);
```
Comment (again4you) [inline gst/nnstreamer/tensor_source/tensor_src_iio.c]: Nice Catch!
