### PR TITLE
[Bug Fix] fix unused variables bug - @open sesame 12/04 20:34

### LINKED ISSUE #957: [Build] Buildfailure when enabling 'CMAKE_BUILD_TYPE=Release'
## Issue Description
If `CMAKE_BUILD_TYPE=Release` is defined when running cmake command, `unused variable` occurs as below. The main reason is that **NDEBUG** is automatically defined when building `Release` mode

## How to Reproduce

```bash
$ mkdir build & cd build
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ make
```

## Error message

```bash
[ 69%] Built target nnstreamer_customfilter_scaler_allocator
/home/again4you/nnstreamer_work/ref_repo/nnstreamer/nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c: In function ‘set_inputDim’:
/home/again4you/nnstreamer_work/ref_repo/nnstreamer/nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c:61:12: error: unused variable ‘data’ [-Werror=unused-variable]
   pt_data *data = private_data;
            ^
[ 72%] Built target nnstreamer_customfilter_opencv_scaler
/home/again4you/nnstreamer_work/ref_repo/nnstreamer/nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c: In function ‘pt_invoke’:
/home/again4you/nnstreamer_work/ref_repo/nnstreamer/nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c:112:12: error: unused variable ‘data’ [-Werror=unused-variable]
   pt_data *data = private_data;
            ^
```

### PR DESCRIPTION
**Pull request by helloahn**
it resolves #957

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

Signed-off-by: HyoungjooAhn <hello.ahnn@gmail.com>

### CODE REVIEW

File: nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c [hunk 1]
```diff
@@ -58,9 +58,7 @@ set_inputDim (void *private_data, const GstTensorFilterProperties * prop,
     const GstTensorsInfo * in_info, GstTensorsInfo * out_info)
 {
   int i;
-  pt_data *data = private_data;
 
-  assert (data);
```
Comment (myungjoo) [inline nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c]: You can assert private_data directly (removing data declaration) without worrying about the release build warnings.
