### PR TITLE
 [Filter/Tensorflow] fix bug of testcase

### LINKED ISSUE #1269: [Test/Tensorflow] a critical error is occurred during test
I detected the below error today.

```bash
nnstreamer_filter_tensorflow$ ssat

...

** (gst-launch-1.0:32187): CRITICAL **: 21:29:03.810: Failed to run model: Invalid argument: Expects arg[0] to be string but int16 is provided

```

The exact location of the error message is here.
https://github.com/nnsuite/nnstreamer/blob/07d627271889e9f1503ad2da742d688181979d79/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc#L495

it's related with the second test case of tensorflow.
https://github.com/nnsuite/nnstreamer/blob/07d627271889e9f1503ad2da742d688181979d79/tests/nnstreamer_filter_tensorflow/runTest.sh#L37-L39

### PR DESCRIPTION
**Pull request by helloahn**
Since the `STRING` input tensors should be processed differently(cannot be done with `C_API`),
the logic was fixed.

it resolves #1269 

Signed-off-by: Hyoung Joo Ahn <hello.ahn@samsung.com>

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

File: ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc [hunk 1]
```diff
@@ -443,52 +451,53 @@ TFCore::run (const GstTensorMemory * input, GstTensorMemory * output)
...
   }
 
   Status run_status =
       session->Run (input_feeds, output_tensor_names, {}, &outputs);
 
-  if (mem_optmz) {
-    TensorBuffer *buf = TensorCApi::Buffer (in);
-    buf->Unref();
+  for (int i = 0; i < inputTensorMeta.num_tensors; ++i) {
+    if (mem_optmz && input_feeds[i].second.dtype() != DT_STRING){
```
Comment (myungjoo) [inline ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc]: do ```if (mem_optmz)``` out of the for loop.

File: ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc [hunk 2]
```diff
@@ -443,52 +451,53 @@ TFCore::run (const GstTensorMemory * input, GstTensorMemory * output)
...
+          input_tensor_info[i].shape,
+          buf
+        );
+        if (!in.IsAligned ()) {
+          g_critical ("the input tensor %s is not aligned", inputTensorMeta.info[i].name);
+          buf->Unref();
+          return -2;
+        }
+      }
+      else {
```
Comment (myungjoo) [inline ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc]: according to the coding convention, it is ```} else {```.

File: ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc (hunk 1 above)
Comment (helloahn) [reply ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc]: it's applied :)

File: ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc (hunk 2 above)
Comment (helloahn) [reply ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc]: it's fixed :)

File: ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc [hunk 3]
```diff
@@ -190,36 +190,44 @@ TFCore::getTensorTypeFromTF (DataType tfType)
  * @param tType	: the defined type of NNStreamer
  * @return the enum of defined tensorflow::DataType
```
Comment (jaeyun-jung) [inline ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc]: let's change the description (param and return)

Comment (helloahn) [reply ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc]: it's applied :)
