### PR TITLE
[Wait for other PR]  [Transform] Change reaction for the invalid option string @open sesame 2/15 13:45

### LINKED ISSUE #946: [NR11] [Tranform] Handling incorrect options
When we have "unknown" operators in tensor_transform
due to typos or incorrect sequences, sending "WARNING" only
may be insufficient.

We need to determine proper reactions before proceeding.

### PR DESCRIPTION
**Pull request by wooksong**
Resolves #946 

This PR mainly addresses the issue related with reaction for the invalid option string of each transform mode. 
- Using regex, each option string is verified before the pipeline starts. 
- When the option string is invalid, the plug-in explicitly displays error messages using g_critical,
- and then, the pipeline is terminated.
- For the arguments of the 'mode' property, the parameter spec is changed from string to enum so that  the gst-inspect-1.0 command can show the supported modes now.
- Format of the valid option strings for each mode is also added to the description of each mode property.

FYI, after this PR,
```bash
$ gst-inspect-1.0 tensor_transform
Factory Details:
  Rank                     none (0)
  Long-name                TensorTransform
  Klass                    Converter/Filter/Tensor
  Description              Transforms other/tensor dimensions for different models or frameworks
  Author                   MyungJoo Ham <myungjoo.ham@samsung.com>

...omission...
  mode                : Mode used for transforming tensor
                        flags: readable, writable
                        Enum "gtt_mode_type" Default: -1, "unknown"
                           (0): dimchg           - Mode for changing tensor dimensions, option=FROM_DIM:TO_DIM (with a regex, ^([0-3]):([0-3])$, where NNS_TENSOR_RANK_LIMIT is 4)
                           (1): typecast         - Mode for casting type of tensor, option=(^[u]?int(8|16|32|64)$|^float(32|64)$)
                           (2): arithmetic       - Mode for arithmetic operations with tensor, option=[typecast:TYPE,]add|mul|div:NUMBER..., ...
                           (3): transpose        - Mode for transposing shape of tensor, option=D1':D2':D3':D4 (fixed to 3)
                           (4): stand            - Mode for statistical standardization of tensor, option=default
                           (-1): unknown          - Unknown or not-implemented-yet mode
  option              : Option for the tensor transform mode ?
                        flags: readable, writable
                        String. Default: null
...omission...
```
**Changes in this PR**
- v2
  - rebased onto https://github.com/nnsuite/nnstreamer/pull/1119
  - updated error messages to allow breaking 80col rule

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Wook Song <wook16.song@samsung.com>

### CODE REVIEW

File: gst/nnstreamer/tensor_transform/tensor_transform.c [hunk 1]
```diff
@@ -91,6 +91,13 @@
 GST_DEBUG_CATEGORY_STATIC (gst_tensor_transform_debug);
 #define GST_CAT_DEFAULT gst_tensor_transform_debug
 
+#define REGEX_DIMCHG_OPTION "^([0-3]):([0-3])$"
+#define REGEX_TYPECAST_OPTION "(^[u]?int(8|16|32|64)$|^float(32|64)$)"
+#define REGEX_TRANSPOSE_OPTION "^(?:([0-2]):(?!.*\\1)){3}3$"
+#define REGEX_ARITH_OPTION "^(typecast:([u]?int(8|16|32|64)|float(32|64)),)?"\
+    "(((add|mul|div)(:([-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?))+)(,|))+$"
+#define REGEX_ARITH_OPTION_TYPECAST "(typecast:([u]?int(8|16|32|64)|float(32|64)))"
+
```
Comment (myungjoo) [inline gst/nnstreamer/tensor_transform/tensor_transform.c]: 👍

**Comment by wooksong** [comment]
Waiting for merging https://github.com/nnsuite/nnstreamer/pull/1126
